heat_template_version: 2014-10-16
description: An Infoblox Grid Member
parameters:
  mgmt_network:
    type: string
    description: the network for management
  lan1_network:
    type: string
    description: the network for serving protocols
resources:
  lan1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: lan1_network }
  grid_member:
    type: Infoblox::Grid::Member
    properties:
      wapi_url: https://172.16.98.100/wapi/v2.2/
      wapi_username: admin
      wapi_password: infoblox
      wapi_insecure_do_not_verify_certificate: True
      name: nios-test.infoblox.local
      model: IB-VM-810
      LAN1: { get_resource: lan1_port }
      licenses: ["vnios", "dns", "enterprise"]
      temp_licenses: ["vnios", "dns", "enterprise"]
      gm_ip: 172.16.98.100
      gm_certificate: I agree to bypass the SSL Certification checking, thus using UNSECURE connection to the Grid
      nat_ip: 172.16.98.52
      remote_console_enabled: true
      admin_password: foobar
  server:
    type: OS::Nova::Server
    properties:
      flavor: vnios8xx.55
      image: nios-7.2.0-demo-8xx-55.qcow2
      networks: [{network: {get_param: mgmt_network} }, {port: { get_resource: lan1_port}} ]
      user_data_format: RAW
      user_data: { get_attr: [grid_member, user_data] }
outputs:
  member_address:
    value: { get_attr: [lan1_port, fixed_ips] }
  user_data:
    value: { get_attr: [grid_member, user_data] }
